services:
  - type: web
    name: novapress-v2
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false